-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   Author:           Enoch Oppong - D19126484
--   Description:      Catering For Kings Case Study 
--   site/type:        Oracle Database 12c

--ALTER SCHEMA
ALTER SESSION SET CURRENT_SCHEMA = eoppong;

DROP TABLE client CASCADE CONSTRAINTS;

DROP TABLE full_service CASCADE CONSTRAINTS;

DROP TABLE minimum_service CASCADE CONSTRAINTS;

DROP TABLE party_service CASCADE CONSTRAINTS;

DROP TABLE party_service_to_resources CASCADE CONSTRAINTS;

DROP TABLE resources CASCADE CONSTRAINTS;

-- CLIENT TABLE
CREATE TABLE client (
    client_id         NUMBER NOT NULL,
    client_name       VARCHAR2(20),
    client_address    VARCHAR2(50),
    client_number     NUMBER,
    advance_fee       VARCHAR2(10),
    paid_fee          VARCHAR2(10),
    recieved_invoice  VARCHAR2(10)
)
LOGGING;
ALTER TABLE client ADD CONSTRAINT client_pk PRIMARY KEY ( client_id );

--FULL SERVICE TABLE
CREATE TABLE full_service (
    full_service_id                 NUMBER NOT NULL,
    fmain_course                    VARCHAR2(30),
    f_starters                      VARCHAR2(30),
    f_desserts                      VARCHAR2(30),
    client_client_id                NUMBER NOT NULL,
    party_service_party_service_id  NUMBER NOT NULL
)
LOGGING;
ALTER TABLE full_service ADD CONSTRAINT full_service_pk PRIMARY KEY ( full_service_id );

--MINIMUM SERVICE TABLE
CREATE TABLE minimum_service (
    minimum_service_id  NUMBER NOT NULL,
    m_starters          VARCHAR2(30),
    mmain_course        VARCHAR2(30),
    m_coffee            VARCHAR2(30),
    client_client_id    NUMBER NOT NULL
)
LOGGING;
ALTER TABLE minimum_service ADD CONSTRAINT minimum_service_pk PRIMARY KEY ( minimum_service_id );

--PARTY SERVICE TABLE
CREATE TABLE party_service (
    party_service_id  NUMBER NOT NULL,
    pmain_course      VARCHAR2(30),
    p_starters        VARCHAR2(30),
    pcheese_platters  VARCHAR2(30),
    p_desserts        VARCHAR2(30),
    p_beverages       VARCHAR2(30),
    client_client_id  NUMBER NOT NULL
)
LOGGING;
ALTER TABLE party_service ADD CONSTRAINT party_service_pk PRIMARY KEY ( party_service_id );

--PARTY SEERVICE TO RESOURCE TABLE (AUTOMATICALLY CREATED)
CREATE TABLE party_service_to_resources (
    party_service_party_service_id  NUMBER NOT NULL,
    resources_resource_id           NUMBER NOT NULL
)
LOGGING;
ALTER TABLE party_service_to_resources ADD CONSTRAINT party_service_to_resources_pk PRIMARY KEY ( party_service_party_service_id,resources_resource_id );

--RESOURCE TABLE
CREATE TABLE resources (
    resource_id       NUMBER NOT NULL,
    r_cutlery         VARCHAR2(10),
    r_staff           VARCHAR2(10),
    r_vans            VARCHAR2(10),
    r_tableware       VARCHAR2(10),
    r_table           VARCHAR2(10),
    r_chairs          VARCHAR2(10),
    client_client_id  NUMBER NOT NULL
)
LOGGING;
ALTER TABLE resources ADD CONSTRAINT resources_pk PRIMARY KEY ( resource_id );
CREATE UNIQUE INDEX resources__idx ON
    resources (
        client_client_id
    ASC )
        LOGGING;

-- ALTER --> FULL SERVICE
ALTER TABLE full_service
    ADD CONSTRAINT full_service_client_fk FOREIGN KEY ( client_client_id )
        REFERENCES client ( client_id )
    NOT DEFERRABLE;

ALTER TABLE full_service
    ADD CONSTRAINT full_service_party_service_fk FOREIGN KEY ( party_service_party_service_id )
        REFERENCES party_service ( party_service_id )
    NOT DEFERRABLE;

-- ALTER --> MINIMUM SERVICE
ALTER TABLE minimum_service
    ADD CONSTRAINT minimum_service_client_fk FOREIGN KEY ( client_client_id )
        REFERENCES client ( client_id )
    NOT DEFERRABLE;

-- ALTER --> PARTY SERVICE
ALTER TABLE party_service
    ADD CONSTRAINT party_service_client_fk FOREIGN KEY ( client_client_id )
        REFERENCES client ( client_id )
    NOT DEFERRABLE;

-- ALTER --> PARTY_SERVICE TO RESOURCES
ALTER TABLE party_service_to_resources
    ADD CONSTRAINT party_service_to_resources_party_service_fk FOREIGN KEY ( party_service_party_service_id )
        REFERENCES party_service ( party_service_id )
    NOT DEFERRABLE;

ALTER TABLE party_service_to_resources
    ADD CONSTRAINT party_service_to_resources_resources_fk FOREIGN KEY ( resources_resource_id )
        REFERENCES resources ( resource_id )
    NOT DEFERRABLE;


ALTER TABLE resources
    ADD CONSTRAINT resources_client_fk FOREIGN KEY ( client_client_id )
        REFERENCES client ( client_id )
    NOT DEFERRABLE;


-- Automatically Generated by Data Modeler
-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             1
-- ALTER TABLE                             13

